name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # This will trigger the workflow for any tag creation
  # workflow_dispatch:

jobs:
 deploy-to-gke:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate with GKE
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - name: Set up kubectl
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: vibrant-victory-452605-p3

    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin
        gcloud auth configure-docker

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials cluster-1 --zone us-central1-c --project vibrant-victory-452605-p3

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/nginx nginx=redis
        kubectl rollout status deployment/nginx
