name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'  # This will trigger the workflow for any tag creation

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java (Maven)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build the Maven project
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/myjava:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/myjava:${{ github.ref_name }}  # Use the tag as the image tag

      # Optional: Post-build cleanup (if needed)
      - name: Post-build cleanup
        run: docker image prune -f

